# Generated by Django 5.0.14 on 2026-05-02 19:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Aluflow Glass & Aluminium", max_length=200
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="branding/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="Zimbabwe", max_length=100)),
                ("tax_number", models.CharField(blank=True, max_length=50)),
                ("bank_details", models.TextField(blank=True)),
                (
                    "default_vat_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=5
                    ),
                ),
                ("currency_symbol", models.CharField(default="$", max_length=5)),
                ("currency_code", models.CharField(default="USD", max_length=10)),
            ],
            options={
                "verbose_name": "Company profile",
                "verbose_name_plural": "Company profile",
            },
        ),
    ]
