# Generated by Django 5.0.14 on 2026-05-08 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        help_text="Frozen actor name in case the user is later deleted/renamed.",
                        max_length=200,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("status_change", "Status changed"),
                            ("approve", "Approved"),
                            ("reject", "Rejected"),
                            ("send", "Sent"),
                            ("payment", "Payment recorded"),
                            ("lead_converted", "Lead converted to customer"),
                            ("quote_approved", "Quote approved"),
                            ("login", "Logged in"),
                            ("login_failed", "Failed login"),
                            ("logout", "Logged out"),
                            ("webhook", "Created via webhook"),
                            ("note", "Note"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_app", models.CharField(blank=True, max_length=60)),
                ("target_model", models.CharField(blank=True, max_length=60)),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=60),
                ),
                ("target_repr", models.CharField(blank=True, max_length=300)),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
                "indexes": [
                    models.Index(
                        fields=["target_app", "target_model", "target_id"],
                        name="audit_audit_target__a4b646_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="audit_audit_action_e33994_idx",
                    ),
                ],
            },
        ),
    ]
